### ISSUE TITLE
just crash on ios 15.1.0

### ISSUE THREAD

**Issue by fallbort** [robbiehanson/CocoaAsyncSocket#779]
Crashed: GCDAsyncSocket-CFStream
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
0
libobjc.A.dylib
lookUpImpOrForward + 76
1
libobjc.A.dylib
_objc_msgSend_uncached + 68
2
Foundation
-[_NSThreadPerformInfo dealloc] + 56
3
Foundation
__NSThreadPerformPerform + 240
4
CoreFoundation
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
5
CoreFoundation
__CFRunLoopDoSource0 + 208
6
CoreFoundation
__CFRunLoopDoSources0 + 268
7
CoreFoundation
__CFRunLoopRun + 820
8
CoreFoundation
CFRunLoopRunSpecific + 600
9
Foundation
-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
10
MeMe
GCDAsyncSocket.m - Line 7686
+[GCDAsyncSocket cfstreamThread:] + 7686
11
Foundation
__NSThread__start__ + 808
12
libsystem_pthread.dylib
_pthread_start + 148
13
libsystem_pthread.dylib
thread_start + 8

a lot of people crashed,and just crash on ios 15.1.0

**Comment by Jusung** [comment]
Same crash happens on iOS 15.1 and above.

**Comment by yangchao110** [comment]
Same crash happens on iOS 15.1 or above.

0 libobjc.A.dylib 0x0000000198c62bf0 objc_release + 6858080256
1 Foundation 0x0000000181dc73e4 __NSThreadPerformPerform (in Foundation) + 240
2 CoreFoundation 0x0000000180623020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ (in CoreFoundation) + 28
3 CoreFoundation 0x0000000180633ce0 __CFRunLoopDoSource0 (in CoreFoundation) + 208
4 CoreFoundation 0x000000018056dfe8 __CFRunLoopDoSources0 (in CoreFoundation) + 268
5 CoreFoundation 0x00000001805737f4 __CFRunLoopRun (in CoreFoundation) + 820
6 CoreFoundation 0x00000001805873b8 CFRunLoopRunSpecific + 6448119808
7 Foundation 0x0000000181da2354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] (in Foundation) + 236
8 TuJia 0x0000000101558680 +[GCDAsyncSocket cfstreamThread] + 360

**Comment by jmichael218** [comment]
same crash on iOS 15.1

**Comment by yyj1993322** [comment]
Same issue +1

**Comment by yyj1993322** [comment]
same crash on iOS 15.1.0 and CocoaAsyncSocket 7.6.4, what can i do

**Comment by fenglianhua** [comment]
Same crash happens on iOS 15.1 and above.

**Comment by jmichael218** [comment]
Same crash on iOS 15.1 and  CocoaAsyncSocket 7.6.5 (was 7.6.4)

**Comment by shanglina** [comment]
Same crash on iOS 15.1 and CocoaAsyncSocket 7.6.5 and 7.6.4 what can i do

**Comment by nispring** [comment]
Same crash happens on iOS 15.1 and above.

**Comment by CommandB** [comment]
when I in background ,it crash,can you look it and improve

**Comment by jmichael218** [comment]
is there anyone has solved the crash problem?

**Comment by tangguoan** [comment]
同样遇见这种崩溃，谁有解决方案吗？

**Comment by sxxjxxhxxn** [comment]
@fallbort
it looks like [same issue](https://github.com/robbiehanson/CocoaAsyncSocket/issues/775#issuecomment-958171806)

**Comment by yangchao110** [comment]
what can I do ?

**Comment by Mench89** [comment]
We have had this crash for ages but it only happened rarely. It increased a lot after iOS 15.1. After some investigation we found, in our own codebase, that we in some cases forgot to call `disconnect` on a GCDAsyncSocket. When we fixed these problems and actually closed all sockets the crash seems to have gone away. So, even if the bug is in GCDAsyncSocket (or actually Apples codebase, according to Apple themselves) then it could be good to make sure that all `connect` and `disconnect`-calls are done correctly.

**Comment by moleculo27** [comment]
I went through my code and matched connect with disconnect calls as suggested by Mench89, but my code still crashes on iOS 15.1. Any help is appreciated.

**Comment by Jusung** [comment]
@chrisballinger @robbiehanson 
Can you guys help us? Please...

**Comment by sxxjxxhxxn** [comment]
static `cfstreamThread` uses `[NSRunLoop currentRunLoop], [NSThread currentThread]`, and
At [NSRunLoop Apple Doc](https://developer.apple.com/documentation/foundation/nsrunloop)..
> **Warning**
> The NSRunLoop class is generally **not thread-safe**, and you must call its methods only within the context of the current thread. **Don’t call the methods of a NSRunLoop object running in a different thread, which might cause unexpected results**

If multiple STOMPClients (with GCDAsyncSocket) exist at same time, it can occur `BAD ACCESS`.
So, matching `connect`, `disconnect` pair is definitely necessary because redundant `connect` increases reference count of STOMPClient.
And you may need an additional refactoring to init the next STOMPClient after deinit of the previous one.

**Comment by moleculo27** [comment]
> I went through my code and matched connect with disconnect calls as suggested by Mench89, but my code still crashes on iOS 15.1. Any help is appreciated.

After reading the comment posted by @sxxjxxhxxn, it occurred to me that my calls may be from separate threads. So I added an async block around my connection code and the issue went away!

```
DispatchQueue.main.async {
	// Connect to the server
	self.bsocket = GCDAsyncSocket(delegate: self, delegateQueue: self.serialQueue)
	
	let port: UInt16 = self.getPort()
	let address: String = self.getAddress()
	
	do {
		try self.bsocket.connect(toHost: address, onPort: port, withTimeout: 5.0)

	} catch {
		// Failed
		print("socket.connectToHost: Error")
		
		self.handleFailedConnectToServer()
		return
	}
}

```

**Comment by fallbort** [comment]
> static `cfstreamThread` uses `[NSRunLoop currentRunLoop], [NSThread currentThread]`, and At [NSRunLoop Apple Doc](https://developer.apple.com/documentation/foundation/nsrunloop)..
> 
> > **Warning**
> > The NSRunLoop class is generally **not thread-safe**, and you must call its methods only within the context of the current thread. **Don’t call the methods of a NSRunLoop object running in a different thread, which might cause unexpected results**
> 
> If multiple STOMPClients (with GCDAsyncSocket) exist at same time, it can occurs `BAD ACCESS`. So, matching `connect`, `disconnect` pair is certainly necessary because redundant `connect` increases reference count of STOMPClient. And you may need an additional refactoring to init the next STOMPClient after deinit of the previous STOMPClient.

we adjust code,and it worked!

**Comment by dustturtle** [comment]
Does anybody have a demo which can reproduce this case inevitably?

**Comment by supanat-toy** [comment]
> > static `cfstreamThread` uses `[NSRunLoop currentRunLoop], [NSThread currentThread]`, and At [NSRunLoop Apple Doc](https://developer.apple.com/documentation/foundation/nsrunloop)..
> > > **Warning**
> > > The NSRunLoop class is generally **not thread-safe**, and you must call its methods only within the context of the current thread. **Don’t call the methods of a NSRunLoop object running in a different thread, which might cause unexpected results**
> > 
> > 
> > If multiple STOMPClients (with GCDAsyncSocket) exist at same time, it can occurs `BAD ACCESS`. So, matching `connect`, `disconnect` pair is certainly necessary because redundant `connect` increases reference count of STOMPClient. And you may need an additional refactoring to init the next STOMPClient after deinit of the previous STOMPClient.
> 
> we adjust code,and it worked!

How to fix it ? Can you show and explain your code.

**Comment by drunkbread** [comment]
Same crash on iOS 15.1 and CocoaAsyncSocket 7.6.5

**Comment by iosbuger** [comment]
Same crash, and it's fixed after the deadlock broken.
我也遇到这个崩溃，修复掉下面的死锁后，这个崩溃没有了。

> Thread 14:
0   libsystem_kernel.dylib        	0x00000001b75ecc54 kevent_id + 8
1   libdispatch.dylib             	0x00000001802e1eac _dispatch_kq_poll + 228 (event_kevent.c:750)
2   libdispatch.dylib             	0x00000001802e2904 _dispatch_event_loop_wait_for_ownership + 444 (event_kevent.c:2221)
3   libdispatch.dylib             	0x00000001802ceb80 __DISPATCH_WAIT_FOR_QUEUE__ + 336 (queue.c:1678)
4   libdispatch.dylib             	0x00000001802ce744 _dispatch_sync_f_slow + 144 (queue.c:1762)
5   xxxx                        	0x000000010252000c -[GCDAsyncSocket removeStreamsFromRunLoop] + 92 (GCDAsyncSocket.m:7987)
6   xxxx                        	0x0000000102517648 -[GCDAsyncSocket closeWithError:] + 184 (GCDAsyncSocket.m:3223)
7   libdispatch.dylib             	0x00000001802bf660 _dispatch_client_callout + 20 (object.m:560)
8   libdispatch.dylib             	0x00000001802ce8b4 _dispatch_lane_barrier_sync_invoke_and_complete + 56 (queue.c:1016)
9   xxxx                        	0x000000010251200c -[GCDAsyncSocket dealloc] + 128 (GCDAsyncSocket.m:1047)
10  Foundation                    	0x0000000181e1b8d4 -[_NSThreadPerformInfo dealloc] + 56 (NSThread.m:270)
11  Foundation                    	0x0000000181e133e4 __NSThreadPerformPerform + 240 (NSThread.m:1071)
12  CoreFoundation                	0x000000018066f020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1972)
13  CoreFoundation                	0x000000018067fce0 __CFRunLoopDoSource0 + 208 (CFRunLoop.c:2016)
14  CoreFoundation                	0x00000001805b9fe8 __CFRunLoopDoSources0 + 268 (CFRunLoop.c:2053)
15  CoreFoundation                	0x00000001805bf7f4 __CFRunLoopRun + 820 (CFRunLoop.c:2951)
16  CoreFoundation                	0x00000001805d33b8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
17  Foundation                    	0x0000000181dee354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236 (NSRunLoop.m:373)
18  xxxx                        	0x000000010251f98c +[GCDAsyncSocket cfstreamThread:] + 372 (GCDAsyncSocket.m:7686)
19  Foundation                    	0x0000000181e3e36c __NSThread__start__ + 808 (NSThread.m:972)
20  libsystem_pthread.dylib       	0x00000001f11d69a4 _pthread_start + 148 (pthread.c:891)
21  libsystem_pthread.dylib       	0x00000001f11d5ea0 thread_start + 8

- +[GCDAsyncSocket cfstreamThread:] is in cfstreamThreadSetupQueue
- -[GCDAsyncSocket dealloc] dispatch_sync socketQueue
-  -[GCDAsyncSocket removeStreamsFromRunLoop] dispatch_sync cfstreamThreadSetupQueue

It's deadlock.
这边死锁了。

To break the deadlock you need to ensure that the dealloc is not in cfstreamThreadSetupQueue, and the reference count is reduced to 0 on other threads. After the following delegate callback, then release the GCDAsyncSocket object.
要打破死锁，需要保证dealloc不在cfstreamThreadSetupQueue，引用计数在其他线程减为0，即 在下面这个delegate回调后，再释放GCDAsyncSocket对象。
- (void)socketDidDisconnect:(GCDAsyncSocket *)sock withError:(nullable NSError *)err;

**Comment by wso986** [comment]
Same crash happens on iOS 15.1 and above.

**Comment by sunbohong** [comment]
@wso986
 该PR是否能够修复？
Have you try this PR?
 https://github.com/robbiehanson/CocoaAsyncSocket/pull/785 

原理分析：
 https://mp.weixin.qq.com/s?src=11&timestamp=1644057491&ver=3602&signature=gpQA2q2uCWqvjcyZUMPrCmebRFEnTtZ-8IxK0ospoijfIw9yLSF1f91Qn6jpR7M9u5b4-myI7950SWwcWeo3wea*qraHlTnRcBehLjhJXyHAzZpEdTQrB8UrE5sfeWkE&new=1

**Comment by nguyenhuutinh** [comment]
better change to use NWNetwork. this library is out of date long time ago

**Comment by datavisoryuechen** [comment]
> 



> @wso986 该PR是否能够修复？ Have you try this PR? #785
> 
> 原理分析： https://mp.weixin.qq.com/s?src=11&timestamp=1644057491&ver=3602&signature=gpQA2q2uCWqvjcyZUMPrCmebRFEnTtZ-8IxK0ospoijfIw9yLSF1f91Qn6jpR7M9u5b4-myI7950SWwcWeo3wea*qraHlTnRcBehLjhJXyHAzZpEdTQrB8UrE5sfeWkE&new=1

 这个原理分析的链接打不开，能再发一个吗？谢谢

**Comment by sunbohong** [comment]
https://mp.weixin.qq.com/s/Tn8SN1eNaGkR1ddEKTkzPQ



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 8, 2022 18:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [robbiehanson/CocoaAsyncSocket] just crash on ios 15.1.0 (Issue #779)




    
@wso986 该PR是否能够修复？ Have you try this PR? #785
 
原理分析： https://mp.weixin.qq.com/s?src=11&amp;timestamp=1644057491&amp;ver=3602&amp;signature=gpQA2q2uCWqvjcyZUMPrCmebRFEnTtZ-8IxK0ospoijfIw9yLSF1f91Qn6jpR7M9u5b4-myI7950SWwcWeo3wea*qraHlTnRcBehLjhJXyHAzZpEdTQrB8UrE5sfeWkE&amp;new=1
  
这个原理分析的链接打不开，能再发一个吗？谢谢
